# Generated by Django 3.0.2 on 2020-03-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joindate', models.DateTimeField(auto_now_add=True)),
                ('date_birth', models.DateField()),
                ('profile', models.ImageField(default='GED/img_profile/rien.jpg', upload_to='GED/img_profile/')),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10)),
                ('about', models.TextField(max_length=250)),
                ('filiere', models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('AERO', 'AERO'), ('TC', 'TC')], max_length=50)),
                ('niveau', models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=50)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('avertissement', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('tache', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('tache_time', models.TimeField(null=True)),
                ('state', models.BooleanField(default=False)),
                ('eleve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=45, unique=True)),
                ('annee', models.IntegerField()),
                ('epreuve', models.FileField(unique=True, upload_to='GED/sujets')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joindate', models.DateTimeField(auto_now_add=True)),
                ('date_birth', models.DateField(null=True)),
                ('profile', models.ImageField(default='GED/img_profile/rien.jpg', upload_to='GED/img_profile/')),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10)),
                ('about', models.TextField(max_length=250)),
                ('userp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifs', models.CharField(max_length=45)),
                ('time_notif', models.DateTimeField(auto_now_add=True)),
                ('eleve_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve')),
                ('prof_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_fichier', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('type', models.CharField(choices=[('image', 'png'), ('document', 'fichiers')], max_length=25, null=True)),
                ('filiere', models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('AERO', 'AERO'), ('TC', 'TC')], default='GIT', max_length=45)),
                ('matiere', models.CharField(choices=[('MATHEMATIQUES', 'MATHS'), ('PHYSIQUE', 'PHYSIQUE'), ('ANALYSE DE DONNÉES', 'ANALYSE DE DONNÉES')], max_length=50)),
                ('niveau', models.CharField(blank=True, max_length=8, null=True)),
                ('fichier', models.FileField(unique=True, upload_to='GED/documents')),
                ('updload_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.BooleanField(default=False)),
                ('note', models.IntegerField(default=0)),
                ('share', models.BooleanField(default=False)),
                ('eleve_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve')),
                ('prof_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=350, null=True)),
                ('date_comments', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GED.Document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve')),
            ],
        ),
    ]
