# Generated by Django 3.0.3 on 2020-02-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='profile',
            field=models.ImageField(default='GED/img_profile/rien.jpg', upload_to='GED/img_profile/'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='profile',
            field=models.ImageField(default='GED/img_profile/rien.jpg', upload_to='GED/img_profile/'),
        ),
    ]
