# Generated by Django 3.0.3 on 2020-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='matiere',
            field=models.CharField(choices=[('MATHEMATIQUES', 'MATHS'), ('PHYSIQUE', 'PHYSIQUE'), ('ANALYSE DE DONNÉES', 'ANALYSE DE DONNÉES'), ('DJANGO', 'DJANGO'), ('UML', 'UML'), ('HERO', 'HERO'), ('ALGEBRE', 'ALGEBRE')], max_length=50),
        ),
    ]
