# Generated by Django 3.0.3 on 2020-09-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0002_auto_20200415_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='date_birth',
        ),
        migrations.AddField(
            model_name='tache',
            name='prof_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Professeur'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('.bmp', '.bmp'), ('.gif', '.gif'), ('.ico', '.ico'), ('.ief', '.ief'), ('.jpe', '.jpe'), ('.jpeg', '.jpeg'), ('.jpg', '.jpg'), ('.pbm', '.pbm'), ('.pgm', '.pgm'), ('.png', '.png'), ('.pnm', '.pnm'), ('.ppm', '.ppm'), ('.ras', '.ras'), ('.rgb', '.rgb'), ('.svg', '.svg'), ('.tif', '.tif'), ('.tiff', '.tiff'), ('.xbm', '.xbm'), ('.xpm', '.xpm'), ('.xwd', '.xwd'), ('.pdf', '.pdf'), ('.zip', '.zip'), ('.ppt', '.ppt'), ('.djvu', '.djvu'), ('.txt', '.txt'), ('.docx', '.docx')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='joindate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='joindate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='eleve_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve'),
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('eleve_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve')),
                ('prof_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Professeur')),
            ],
        ),
    ]
