# Generated by Django 3.0.3 on 2020-03-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0002_auto_20200304_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notifs',
            field=models.CharField(max_length=150),
        ),
    ]
