# Generated by Django 3.0.2 on 2020-03-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0002_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='eleve_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='prof_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GED.Professeur'),
        ),
    ]
