# Generated by Django 3.0.2 on 2020-03-02 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0003_auto_20200302_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time_notif',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
