# Generated by Django 3.0.3 on 2020-09-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0003_auto_20200906_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('.bmp', '.bmp'), ('.gif', '.gif'), ('.ico', '.ico'), ('.ief', '.ief'), ('.jpe', '.jpe'), ('.jpeg', '.jpeg'), ('.jpg', '.jpg'), ('.pbm', '.pbm'), ('.pgm', '.pgm'), ('.png', '.png'), ('.pnm', '.pnm'), ('.ppm', '.ppm'), ('.ras', '.ras'), ('.rgb', '.rgb'), ('.svg', '.svg'), ('.tif', '.tif'), ('.tiff', '.tiff'), ('.xbm', '.xbm'), ('.xpm', '.xpm'), ('.xwd', '.xwd'), ('.pdf', '.pdf'), ('.zip', '.zip'), ('.ppt', '.ppt'), ('.djvu', '.djvu'), ('.txt', '.txt'), ('.docx', '.docx'), ('.mlx', '.mlx')], max_length=25, null=True),
        ),
    ]
