# Generated by Django 3.0.3 on 2020-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0004_auto_20200906_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='network',
            field=models.CharField(choices=[('facebook', 'facebook'), ('twitter', 'twitter'), ('google', 'google'), ('linkedin', 'linkedin'), ('instragram', 'instragram')], max_length=100),
        ),
    ]
