# Generated by Django 3.0.3 on 2020-02-24 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0005_auto_20200223_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(max_length=360),
        ),
        migrations.AlterField(
            model_name='document',
            name='filiere',
            field=models.CharField(choices=[('GIT', 'GENIE INFORMATIQUE ET TELECOMMUNICATION'), ('GEM', 'GENIE ELECTRO-MÉCANIQUE'), ('GC', 'GÉNIE CIVIL'), ('AERO', 'GÉNIE AÉRONAUTIQUE'), ('TC', 'TRONC-COMMUN')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='niveau',
            field=models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GED.Document')),
                ('eleve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GED.Eleve')),
            ],
            options={
                'unique_together': {('eleve_id', 'document')},
                'index_together': {('eleve_id', 'document')},
            },
        ),
    ]
