# Generated by Django 3.0.3 on 2020-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0005_auto_20200907_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='network',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('google', 'Google'), ('linkedin', 'Linkedin'), ('instragram', 'Instragram')], max_length=100),
        ),
    ]
