# Generated by Django 3.0.3 on 2020-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0006_auto_20200224_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='filiere',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('AERO', 'AERO'), ('TC', 'TC')], default='None', max_length=50),
        ),
    ]
