# Generated by Django 3.0.3 on 2020-02-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0007_auto_20200224_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploader',
        ),
    ]
