# Generated by Django 3.0.3 on 2020-09-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0007_auto_20200907_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='tache_time',
            field=models.DateField(null=True),
        ),
    ]
