# Generated by Django 3.0.3 on 2020-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0009_auto_20200908_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_comments',
            field=models.DateField(auto_now_add=True),
        ),
    ]
