# Generated by Django 3.0.3 on 2020-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GED', '0010_auto_20200301_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='filiere',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GEM'), ('GC', 'GC'), ('AERO', 'AERO'), ('TC', 'TC')], default='TC', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='niveau',
            field=models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], default='TC', max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='filiere',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GEM', 'GIT'), ('GC', 'GIT'), ('AERO', 'AERO'), ('TC', 'TC')], default='TC', max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='niveau',
            field=models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], default='TC', max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
